//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.11 at 04:23:04 PM WEST 
//


package toDatabase;

import java.io.Serializable;
import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;




@Entity
public class DbNews implements Serializable{
	
	private static final long serialVersionUID = 1L;
	 @Id @GeneratedValue(strategy=GenerationType.AUTO)	 
	protected long chave;
	protected BigInteger id;
    @Column(columnDefinition="TEXT")
    protected String title;
    @Column(columnDefinition="TEXT")
    protected String url;
    @Column(columnDefinition="TEXT")
    protected String highlits;
    @Column(columnDefinition="TEXT")
    protected String author;
    //@Column(columnDefinition="LONGTEXT")
    @Column(columnDefinition="TEXT")
    protected String text;
    @Column(columnDefinition="TEXT")
    protected String photos;
    @Column(columnDefinition="TEXT")
    protected String video;
	protected int day;
    @Column(columnDefinition="TEXT")
    protected String month;
    protected int year;
    protected Integer time;
    @ManyToOne DbRegion dbRegion;
    
    public DbNews(){
    	super();
    }
    
   
    public DbNews(long chave, BigInteger id, String title, String url,
			String highlits, String author, String text, String photos,
			String video, int day, String month, int year, Integer time,
			DbRegion dbRegion) {
		super();
		this.chave = chave;
		this.id = id;
		this.title = title;
		this.url = url;
		this.highlits = highlits;
		this.author = author;
		this.text = text;
		this.photos = photos;
		this.video = video;
		this.day = day;
		this.month = month;
		this.year = year;
		this.time = time;
		this.dbRegion = dbRegion;
	}
    

	public DbRegion getDbRegion() {
		return dbRegion;
	}


	public void setDbRegion(DbRegion dbRegion) {
		this.dbRegion = dbRegion;
	}


	public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the highlits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighlits() {
        return highlits;
    }

    /**
     * Sets the value of the highlits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighlits(String value) {
        this.highlits = value;
    }

    public String getAuthor() {
        return author;
    }

  
    public void setAuthor(String value) {
        this.author = value;
    }

   
    public String getText() {
        return text;
    }

    public void setText(String value) {
        this.text = value;
    }

    public String getPhotos() {
        return photos;
    }


    public void setPhotos(String value) {
        this.photos = value;
    }

    public void setVideo(String value) {
        this.video = value;
    }

    public String getVideo() {
        return video;
    }

    
    public BigInteger getId() {
        return id;
    }

  
    public void setId(BigInteger value) {
        this.id = value;
    }
    public int getDay() {
  		return day;
  	}
  	public void setDay(int day) {
  		this.day = day;
  	}
  	public String getMonth() {
  		return month;
  	}
  	public void setMonth(String month) {
  		this.month = month;
  	}
  	public int getYear() {
  		return year;
  	}
  	public void setYear(int year) {
  		this.year = year;
  	}
  	public Integer getTime() {
  		return time;
  	}
  	public void setTime(Integer time) {
  		this.time = time;
  	}
  	public DbRegion getRegion() {
  		return dbRegion;
  	}
  	public void setRegion(DbRegion region) {
  		this.dbRegion = region;
  	}
  	public static long getSerialversionuid() {
  		return serialVersionUID;
  	}
  	 public long getChave() {
 		return chave;
 	}
 	public void setChave(long chave) {
 		this.chave = chave;
 	}

}
