//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.11 at 04:23:04 PM WEST 
//


package toDatabase;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;


@Entity
public class DbRegion  implements Serializable{
	 private static final long serialVersionUID = 1L;
	 @Id @GeneratedValue(strategy=GenerationType.AUTO)	int id;
	protected String area;
    @OneToMany(mappedBy="dbRegion") List<DbNews> news;
   
    public DbRegion(){
      	super();
    }
    

    public DbRegion(String area, List<DbNews> news) {
		super();
		this.area = area;
		this.news = news;
	}


	public void setNews(List<DbNews> news) {
		this.news = news;
	}


    public List<DbNews> getNews() {
        if (news == null) {
            news = new ArrayList<DbNews>();
        }
        return this.news;
    }


    public String getArea() {
        return area;
    }


    public void setArea(String value) {
        this.area = value;
    }
    public static long getSerialversionuid() {
    	  return serialVersionUID;
    	 }

}
