/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author christophe
 */
import java.io.*; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
public class Nome extends javax.swing.JFrame {
    int pontuação;
    /**
     * Creates new form Nome
     */
    public Nome() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ok_button = new javax.swing.JButton();
        Cancel_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        n_jogador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Ok_button.setText("Ok");
        Ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ok_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Ok_button);
        Ok_button.setBounds(10, 140, 70, 27);

        Cancel_button.setText("Cancel");
        Cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_button);
        Cancel_button.setBounds(100, 140, 70, 27);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 243, 243));
        jLabel1.setText("Insira o seu nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 260, 29);

        n_jogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_jogadorActionPerformed(evt);
            }
        });
        getContentPane().add(n_jogador);
        n_jogador.setBounds(10, 70, 270, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweper/Rainbow_waves_computer_background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 340, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_buttonActionPerformed
        Minsweper inicio = new Minsweper();
    }//GEN-LAST:event_Cancel_buttonActionPerformed

    private void n_jogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_jogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_jogadorActionPerformed

    private void Ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ok_buttonActionPerformed

    String nome = n_jogador.getText();
   
    
    File_handler fW = new File_handler();
        try {
            fW.abre_escrita("Scores.txt");
        } catch (IOException ex) {
            Logger.getLogger(Nome.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fW.escreve_linha(nome);
        } catch (IOException ex) {
            Logger.getLogger(Nome.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fW.escreve_linha(Integer.toString(pontuação));
        } catch (IOException ex) {
            Logger.getLogger(Nome.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fW.fecha_escrita();
        } catch (IOException ex) {
            Logger.getLogger(Nome.class.getName()).log(Level.SEVERE, null, ex);
        }
    Minsweper inicio = new Minsweper();
    }//GEN-LAST:event_Ok_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_button;
    private javax.swing.JButton Ok_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField n_jogador;
    // End of variables declaration//GEN-END:variables
}
