
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NewsSoupService", targetNamespace = "http://soaptoflow/", wsdlLocation = "http://localhost:8081/News?wsdl")
public class NewsSoupService
    extends Service
{

    private final static URL NEWSSOUPSERVICE_WSDL_LOCATION;
    private final static WebServiceException NEWSSOUPSERVICE_EXCEPTION;
    private final static QName NEWSSOUPSERVICE_QNAME = new QName("http://soaptoflow/", "NewsSoupService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/News?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEWSSOUPSERVICE_WSDL_LOCATION = url;
        NEWSSOUPSERVICE_EXCEPTION = e;
    }

    public NewsSoupService() {
        super(__getWsdlLocation(), NEWSSOUPSERVICE_QNAME);
    }

    public NewsSoupService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEWSSOUPSERVICE_QNAME, features);
    }

    public NewsSoupService(URL wsdlLocation) {
        super(wsdlLocation, NEWSSOUPSERVICE_QNAME);
    }

    public NewsSoupService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEWSSOUPSERVICE_QNAME, features);
    }

    public NewsSoupService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewsSoupService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NewsSoup
     */
    @WebEndpoint(name = "NewsSoupPort")
    public NewsSoup getNewsSoupPort() {
        return super.getPort(new QName("http://soaptoflow/", "NewsSoupPort"), NewsSoup.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewsSoup
     */
    @WebEndpoint(name = "NewsSoupPort")
    public NewsSoup getNewsSoupPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soaptoflow/", "NewsSoupPort"), NewsSoup.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEWSSOUPSERVICE_EXCEPTION!= null) {
            throw NEWSSOUPSERVICE_EXCEPTION;
        }
        return NEWSSOUPSERVICE_WSDL_LOCATION;
    }

}
