
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TranporterService", targetNamespace = "http://soaptoflow/", wsdlLocation = "http://localhost:8081/show?wsdl")
public class TranporterService
    extends Service
{

    private final static URL TRANPORTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANPORTERSERVICE_EXCEPTION;
    private final static QName TRANPORTERSERVICE_QNAME = new QName("http://soaptoflow/", "TranporterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/show?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANPORTERSERVICE_WSDL_LOCATION = url;
        TRANPORTERSERVICE_EXCEPTION = e;
    }

    public TranporterService() {
        super(__getWsdlLocation(), TRANPORTERSERVICE_QNAME);
    }

    public TranporterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANPORTERSERVICE_QNAME, features);
    }

    public TranporterService(URL wsdlLocation) {
        super(wsdlLocation, TRANPORTERSERVICE_QNAME);
    }

    public TranporterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANPORTERSERVICE_QNAME, features);
    }

    public TranporterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TranporterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Tranporter
     */
    @WebEndpoint(name = "TranporterPort")
    public Tranporter getTranporterPort() {
        return super.getPort(new QName("http://soaptoflow/", "TranporterPort"), Tranporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tranporter
     */
    @WebEndpoint(name = "TranporterPort")
    public Tranporter getTranporterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soaptoflow/", "TranporterPort"), Tranporter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANPORTERSERVICE_EXCEPTION!= null) {
            throw TRANPORTERSERVICE_EXCEPTION;
        }
        return TRANPORTERSERVICE_WSDL_LOCATION;
    }

}
